### ISSUE TITLE
NOTICE: plan(multiprocess) and plan(remote) of future are deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [sipss/AlpsNMR#65]
Hi. Please note that `multiprocess` is [deprecated since future 1.20.0 (2020-11-03)](https://future.futureverse.org/news/index.html#future-1200) and will soon be defunct, cf.

https://github.com/sipss/AlpsNMR/search?q=multiprocess

Also, `remote` is [deprecated since future 1.24.0 (2022-02-19)](https://future.futureverse.org/news/index.html#deprecated-and-defunct-1-24-0); use `cluster` instead.

**Comment by zeehio** [comment]
Thanks for the error reporting. All `future` deprecation issues have been fixed.

**Comment by HenrikBengtsson** [comment]
Hi, I just want to make sure 'multiprocess' is cleaned out, because search still shows two uses:

https://github.com/sipss/AlpsNMR/search?q=multiprocess

**Comment by zeehio** [comment]
I removed that reference (which would not be executed anyway). No references to that plan are left :-)

Thank you for all the effort you are putting into tracing down uses of the multiprocess plan. Good luck finishing the removal! :four_leaf_clover:  :muscle:
